{"name": "test_add[Errortestcase]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 9", "trace": "self = <test_calc_shenjian.TestCalc object at 0x000002D5A4902910>, testadd = None, a = 5, b = 5, expected = 9\n\n    @pytest.mark.parametrize(\"a,b,expected\", [(3, 7, 10), (-1, -8, -9), (14, -6, 8),(0.5, 1.6, 2.1), (5, 5 , 9)],\n                             ids=(\"Posi\", \"Nega\", \"Posi&Nega\", \"Float\", \"Errortestcase\"))\n    @pytest.mark.run(order=1)\n    # 调用fixture函数,以及预设参数\n    def test_add(self, testadd, a, b, expected):\n        # 调用add函数,返回的结果保存在result里面（下同）\n        result = self.calc.add(a, b)\n        # 判断result结果是否等于期望的值（下同）\n>       assert result == expected\nE       assert 10 == 9\n\ntest_calc_shenjian.py:21: AssertionError"}, "attachments": [{"name": "stdout", "source": "e7ba98fa-04ff-4287-8d52-3ec08019f755-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "5"}, {"name": "b", "value": "5"}, {"name": "expected", "value": "9"}], "start": 1609298012032, "stop": 1609298012033, "uuid": "0180ab84-a1b4-4410-9bd3-99fea553b74a", "historyId": "02866938a88a749c41615dc7e8ec8553", "testCaseId": "a84b0e4db78790cf5f31a207e778d219", "fullName": "test_calc_shenjian.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_calc_shenjian"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "HZCL2002"}, {"name": "thread", "value": "12744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_shenjian"}]}